# basic options
title: Linden Web Post
author: Linden Author
email: zllu@illinois.edu
description: Linden's post description
twitter_username: lindenlu_twitter
github_username:  zllu2_github

# Build settings
markdown: kramdown
theme: minimal
